on:
  push:
    branches:
      - app
    branches-ignore:
      - dev
      - stage
      - prod
  pull_request:
    branches:
      - app
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest