name: Github Action demo with azure
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  RESOURCE_GROUP_NAME: "github-resource-group"
  RESOURCE_GROUP_LOCATION: "eastus"
  KEYVAULT_NAME: "test10101"
permissions:
  id-token: write
  contents: read
jobs:
    job1:
      runs-on: ubuntu-latest
    #   defaults:
    #     run:
    #       working-directory: app/users
      steps:
        - id: CheckoutRepo
          name: Checkout Repository
          uses: actions/checkout@v3
        - id: AzureAuth
          name: Authenticate With Azure
          uses: azure/login@v1
          with:
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        - id: CheckIfKeyvaultExists
          name: Check if keyvault exists
          run: ./script.sh ${{ env.KEYVAULT_NAME }} ${{ env.RESOURCE_GROUP_LOCATION }} ${{ env.RESOURCE_GROUP_NAME }}